---
title: "P8105_Lect7"
author: "Chuyuan XU"
date: "2025-09-23"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(tidyr)
library(haven)
```

## Pivot Longer

```{r}
pulse_df =
  read_sas("data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

pulse_df_long =
  read_sas("data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
    ) %>%
  mutate(visit = replace(visit, visit == 'bl', '00m'))
```

Another example
```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names()

litters_df_long = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight",
  ) |>
  mutate(gd_time = case_match(
    gd_time,
    "gd0_weight" ~ 0,
    "gd18_weight" ~ 18
  ))
```

## Pivot Wider

```{r create a data set}
analysis_df = 
  tibble(group = c("treatment", "treatment", "control", "control"),
         time = c("pre", "post", "pre", "post"),
         mean = c(4, 10, 4.2, 5))
```

```{r}
analysis_df_wider <- analysis_df |>
  pivot_wider(
    names_from = time,
    values_from = mean
  )
```


## bind tables

```{r}
fellowship_ring = 
  read_excel("data_import_examples/lotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "The Fellowship of the Ring")

two_towers = 
  read_excel("data_import_examples/lotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "The Two Towers")

return_king = 
  read_excel("data_import_examples/lotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "The Return of the King")

lotR <- bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    cols = female:male,
    names_to = 'gender',
    values_to = 'words') |>
  mutate(race = str_to_lower(race)) |>
  select(movie, everything())
```

## join FAS dataset

import 'litters' dataset

```{r}
list.files("data_import_examples")
litters = read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  mutate(weight_gain = gd18_weight - gd0_weight) |>
  separate(
    group, 
    into = c("dose", "day_of_treatment"), 
    sep = 3
  )   # separate the variables into 2, sep= : separate after the 3rd digit
```

import 'pups' dataset

```{r}
pups = read_csv("data_import_examples/FAS_pups.csv", na = c("NA", ".", ""), skip=3) |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2 ~ "female"
    )
  )
```

Join the dataset

```{r}
fas_left =
  left_join(pups, litters, by = 'litter_number')

fas_right =
  right_join(pups, litters, by = 'litter_number')

fas_anti = 
  anti_join(pups, litters, by = 'litter_number')
view(fas_anti)
```



