---
title: "P8105_Lect5: Data Import"
author: "Chuyuan XU"
date: "2025-09-16"
output: html_document
---

# Data Wrangling I: Data Import

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset

```{r}
litters_df <-
    read_csv("data/FAS_litters.csv")
```

look at the data variables

```{r}
names(litters_df)

litters_df = 
    janitor::clean_names(litters_df) # change the name into lowercase
```

look at the whole data

```{r}
litters_df
```

Some skimming?

```{r}
skimr::skim(litters_df)
```

# fix the missing data

```{r}
litters_df2 =
    read_csv("data/FAS_litters.csv", na = c("NA", ".", ""))
```

# Skip some lines

```{r}
pups_df =
    read_csv("data/FAS_pups.csv", 
    skip =3, 
    na = c("NA", ".", "")
    )

pups_df = 
    janitor::clean_names(pups_df)
```

# What should we do to EXCEL?

```{r}
LotR_df1 = 
  read_excel("data/LotR_Words.xlsx")

LotR_df2 = 
  read_excel("data/LotR_Words.xlsx", range="B3:D6")

LotR_df2
```

# SAS table

```{r}
pulse_df =
  read_sas("data/public_pulse_data.sas7bdat")
```

# Why not read.csv

```{r, eval=false}
litters_df_hate =
    read.csv("data/FAS_pups.csv")
```

# export the data

```{r}
write_csv(pulse_df, "data/public_pulse_data.csv")
```

