---
title: "P8105_Lect8"
author: "Chuyuan XU"
date: "2025-09-25"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
```

import data

```{r}
data("weather_df")
```

making the first plot

```{r}
ggplot(
  data = weather_df,
  mapping = aes(x = tmin, y=tmax)
) + 
geom_point()
```

```{r}
weather_df |>
  ggplot(
    mapping = aes(x = tmin, y=tmax)
  ) + 
  geom_point()
```

```{r}
ggp_weather = 
  weather_df |>
    ggplot(
    mapping = aes(x = tmin, y=tmax)
  )

ggp_weather + geom_point()

```

```{r}
ggp_weather = 
  weather_df |>
    ggplot(
    mapping = aes(x = tmin, y=tmax, color = name)
  )

ggp_weather + geom_point()

```

```{r}
weather_df |>
  ggplot(
    mapping = aes(x = tmin, y=tmax, color = name)
  ) + 
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(mapping = aes(x = tmin, y=tmax)) + 
  geom_point(aes(color = name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
```

```{r}
weather_df |>
  ggplot(mapping = aes(x = tmin, y=tmax)) + 
  geom_point(aes(color = name, size = prcp, shape = name), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)
```
learning assessment
Write a code chain that starts with weather_df; focuses only on Central Park, converts temperatures to Fahrenheit, makes a scatterplot of min vs. max temperature, and overlays a linear regression line (using options in geom_smooth())
```{r}
weather_df |>
  filter(name == 'CentralPark_NY') |>
  mutate(
    tmin_f = (tmin*9/5) + 32,
    tmax_f = (tmax*9/5) + 32
  ) |>
  
  ggplot(aes(x = tmin_f, y=tmax_f), size = prcp) + 
  geom_point() +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(
    mapping = aes(x = tmin, y=tmax)
  ) + 
  geom_point(color = "white")
```

univariate plots

```{r}
weather_df |>
  ggplot(aes(x = tmin)) +
  geom_density(alpha = 0.2, aes(fill = name))
```

```{r}
ggp_lect8 =
weather_df |>
  ggplot(aes(x = tmin)) +
  geom_density(alpha = 0.2, aes(fill = name))

ggsave("")
```

